/*
 * SPI_config.h
 *
 *  Created on: July 28, 2023
 *      Author: Mohamed Tarek
 */
#ifndef _SPI_CONFIG_H_
#define _SPI_CONFIG_H_

/* Options:
    1- SPI_PINS_A4_A5_A6_A7
    2- SPI_PINS_A15_B3_B4_B5
*/

#define SPI1_PINS    SPI_PINS_A4_A5_A6_A7

/* Options:
    1- SPI_MSB_FIRST
    2- SPI_LSB_FIRST
*/
#define SPI1_DATA_ORDER     SPI_MSB_FIRST
#define SPI2_DATA_ORDER     SPI_LSB_FIRST

/* Options:
    1- SPI_FIRST_CLOCK_FIRST_CAPTURE
    2- SPI_SECOND_CLOCK_FIRST_CAPTURE
*/
#define SPI1_CLK_PHASE      SPI_SECOND_CLOCK_FIRST_CAPTURE
#define SPI2_CLK_PHASE      SPI_SECOND_CLOCK_FIRST_CAPTURE

/* Options:
    1- SPI_CK_0_WHEN_IDLE
    2- SPI_CK_1_WHEN_IDLE
*/
#define SPI1_CLK_POLARITY      SPI_CK_1_WHEN_IDLE
#define SPI2_CLK_POLARITY      SPI_CK_1_WHEN_IDLE

/* Options:
    1- SPI_BAUDRATE_PRESCALER_2
    2- SPI_BAUDRATE_PRESCALER_4
    3- SPI_BAUDRATE_PRESCALER_8
    4- SPI_BAUDRATE_PRESCALER_16
    5- SPI_BAUDRATE_PRESCALER_32
    6- SPI_BAUDRATE_PRESCALER_64
    7- SPI_BAUDRATE_PRESCALER_128
    8- SPI_BAUDRATE_PRESCALER_256
*/
#define SPI1_BAUDRATE_PRESCALER      SPI_BAUDRATE_PRESCALER_2
#define SPI2_BAUDRATE_PRESCALER      SPI_BAUDRATE_PRESCALER_2

#endif