/*
 * USART_config.h
 *
 *  Created on: July 29, 2023
 *      Author: Mohamed Tarek
 */
#ifndef _USART_CONFIG_H_
#define _USART_CONFIG_H_

#define USART1_BAUDRATE  9600
#define USART1_PARITY_CONTROL   USART_PARITY_CONTROL_ENABLED
#define USART1_PARITY_SELECTION     USART_EVEN_PARITY
#define USART1_CLOCK_POLARITY   USART_CLK_1_WHEN_IDLE
#define USART1_CLOCK_PHASE      USART_SECOND_CLOCK_FIRST_CAPTURE
#define USART1_STOP_BITS        USART_1_STOP_BIT
#define USART1_CLOCK_CONTROL    USART_1_CLOCK_ENABLED

#endif